name: Auto Scrape
on:
  schedule:
    - cron: '30 17 * * *' 
  workflow_dispatch: # Vẫn giữ nút này để bạn bấm chạy tay khi cần

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        env:
          SIMPLESCRAPER_API_KEY: ${{ secrets.SIMPLESCRAPER_API_KEY }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: python update_top10.py
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
